### ISSUE TITLE
[Error] Opening tradelink

### ISSUE THREAD

**Issue by HauNguyen188** [antal-k/csgoempire-deposit-bot#12]
Hi,

There is an error with your tool when it tries to "opening tradelink". I attach the image and the link when it open a new tab for trade link.

'http://null%26csgotrader_send%3Dyour_id_730_2_23189894048/'
![image](https://user-images.githubusercontent.com/84444328/132338614-38352735-67bc-4ad2-9578-485d93dc1a36.png)

Can you help me fix this? 

Thanks a lot!

**Comment by antal-k** [comment]
Hey,

It was on empire side, try now.
