### ISSUE TITLE
Bug: Can't send offer

### ISSUE THREAD

**Issue by Axtoru** [antal-k/csgoempire-deposit-bot#13]
everything is normal but when some offer is coming then can't send offer

**Comment by antal-k** [comment]
Hey,

Can you please elaborate? How do you use the sending function?

**Comment by Axtoru** [comment]
> Hey,
> 
> Can you please elaborate? How do you use the sending function
![5](https://user-images.githubusercontent.com/93724816/140384372-818821b4-a292-41f6-b205-82126d52406f.png)
?
I turned on the tool but when there is an offer on empire, the tool does not automatically send the offer

**Comment by tuanngodoan** [comment]
@antal-k I got same bug, sometime can't send offer but log not show any error... Maybe error from trade url or from retry send offfer 
![Screenshot_47](https://user-images.githubusercontent.com/22950936/191304989-a75eb6c3-ade4-4921-8462-9942f82d1adf.png)

**Comment by tuanngodoan** [comment]
@antal-k Maybe expirce cookie? Because i run bot over 24h
