### ISSUE TITLE
Poll for pending trades as a backup mechanism

### ISSUE THREAD

**Issue by rannmann** [antal-k/csgoempire-deposit-bot#31]
Since Valve can't keep the game coordinator up for more than a few hours a day, I think the bot should [poll a user's trades](https://github.com/OfficialCSGOEmpire/API-Docs#get-active-trades) every ~10 minutes to ensure it wasn't canceled by Steam.  When the GC is having issues trades automatically cancel, but Empire catches this behavior and reverts the status enum meaning the user needs to re-send the trade.

Since this would be fallback behavior, we shouldn't poll it too often.  The main goal would be to prevent failure to deliver item issues rather than trying to have a perfect 0-minute delivery time.

**Comment by easton36** [comment]
Since this is already using `steam-tradeoffer-manager`, we just need to listen for `sentOfferChanged`... unless the uncommon occurrence of that failing as well happens :)

**Comment by easton36** [comment]
#32
